version: '3.9'
services:
  session:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - db:/var/lib/redis
  api:
    build: ./api
    command: npm start
    restart: always
    env_file:
      - ./api/.env
    depends_on:
      - session
    environment:
      - DATABASE_URL=file:./dev.db
      - REDIS_URL=redis://:eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81@session:6379
    ports:
      - 4001:4001
    links:
      - session
  web:
    build: ./web
    command: npm run preview
    environment:
      - VITE_AUTH_API_URL=http://api:4001
    depends_on:
      - api
    links:
      - api
    ports:
      - 5173:5173
volumes:
  db:
    driver: local
